/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package clase_002_programacion;


import modelo.Alumno;
import modelo.conexion;
import java.security.Policy.Parameters;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;

import javax.swing.JOptionPane;

import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.export.JRPdfExporter;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;







/**
 *
 * @author taniao
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
     conexion con  = new conexion();
     public int id;
     
    public interfaz() {
       
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcarnet = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        cbocurso = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnreporte = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTPersonas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtcarnet1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtnombre1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbocurso1 = new javax.swing.JComboBox<>();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("Carnet");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 100, 150, 17);

        jLabel2.setText("Nombre Completo:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 140, 140, 17);
        jPanel1.add(txtcarnet);
        txtcarnet.setBounds(180, 100, 325, 23);
        jPanel1.add(txtnombre);
        txtnombre.setBounds(180, 140, 326, 23);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar);
        btnGuardar.setBounds(40, 270, 131, 23);

        cbocurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sistemas Operativos", "Programacion", "Base de datos" }));
        jPanel1.add(cbocurso);
        cbocurso.setBounds(180, 180, 260, 23);

        jLabel3.setText("Curso");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 190, 34, 17);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Registro de Estudiantes");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 30, 320, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase_002_programacion/img/umg_1.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(510, 50, 220, 130);

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(190, 270, 140, 23);

        jLabel10.setText("Version: 1.0");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(500, 290, 100, 17);

        jLabel11.setText("PRACTICA DE PRESABERES ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(320, 20, 200, 17);

        jTabbedPane1.addTab("Formulario", jPanel1);

        jPanel3.setLayout(null);

        btnreporte.setText("Generar Reporte");
        btnreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreporteActionPerformed(evt);
            }
        });
        jPanel3.add(btnreporte);
        btnreporte.setBounds(270, 80, 180, 90);

        jTabbedPane1.addTab("Reporte", jPanel3);

        jPanel2.setLayout(null);

        jTPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTPersonasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTPersonas);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 190, 690, 100);

        jButton1.setText("Consultar Alumnos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(50, 140, 180, 23);

        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(260, 140, 72, 23);

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(360, 140, 76, 23);

        jLabel6.setText("Carnet");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(40, 20, 150, 17);
        jPanel2.add(txtcarnet1);
        txtcarnet1.setBounds(180, 20, 330, 23);

        jLabel8.setText("Nombre Completo:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(40, 60, 140, 17);
        jPanel2.add(txtnombre1);
        txtnombre1.setBounds(180, 50, 326, 23);

        jLabel9.setText("Curso");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(40, 90, 34, 17);

        cbocurso1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sistemas Operativos", "Programacion", "Base de datos" }));
        jPanel2.add(cbocurso1);
        cbocurso1.setBounds(180, 80, 330, 23);

        jTabbedPane1.addTab("Consultar alumnos", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(28, 12, 750, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            con.conexion_db();
            con.listarAlumnos((DefaultTableModel)jTPersonas.getModel());
        }
        catch (ClassNotFoundException ex) {
            Logger.getLogger(interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporteActionPerformed

        try
        {
            String url= System.getProperty("user.dir");
            String ruta = url+"/src/clase_002_programacion/reportes/reportes.jasper";

            JasperReport reporte = (JasperReport) JRLoader.loadObjectFromFile(ruta);
            con.conexion_db();
           
            
          
            Map parametros = new HashMap();
            parametros.put("Usuario","JOSE VINICIO PEÑA");
            
                    
            
           
             JasperPrint jasperPrint = JasperFillManager.fillReport(reporte,parametros, con.con);

            
            JasperViewer viewer = new JasperViewer(jasperPrint,false);
            viewer.setTitle("Reporte UMG");
            viewer.setVisible(true);

        }
        catch(Exception ex)
        {
            System.out.println("Error de reporte"+ex.getMessage());
        }
    }//GEN-LAST:event_btnreporteActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try{

            con.conexion_db();
            Alumno alumno = new  Alumno();

            alumno.setCarnet(txtcarnet.getText());
            alumno.setNombre(txtnombre.getText());
            alumno.setCurso(cbocurso.getSelectedItem().toString());

            con.guardarAlumno(alumno);
            limpiar();
            JOptionPane.showMessageDialog(null,"Información registradaUMG");

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Error:"+ex.getMessage()+"\nVerifique");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTPersonasMouseClicked
        // TODO add your handling code here:
        
      txtcarnet1.setText((String) jTPersonas.getValueAt(jTPersonas.getSelectedRow(),0));
      txtnombre1.setText((String) jTPersonas.getValueAt(jTPersonas.getSelectedRow(),1));
      cbocurso1.addItem((String) jTPersonas.getValueAt(jTPersonas.getSelectedRow(),2));
      id = Integer.parseInt(jTPersonas.getValueAt(jTPersonas.getSelectedRow(),3).toString());
      
      
      
        
        
    }//GEN-LAST:event_jTPersonasMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Alumno al = new Alumno();
        al.setCarnet(txtcarnet1.getText());
        al.setNombre(txtnombre1.getText());
        al.setCurso(cbocurso1.getSelectedItem().toString());
        conexion c = new conexion();
         try {
             c.conexion_db();
              c.editarAlumno(al, id);
              JOptionPane.showMessageDialog(null,"Actualización correcta");
              jButton1.doClick();
              limpiar_formulario();
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(interfaz.class.getName()).log(Level.SEVERE, null, ex);
         }
       
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    public void limpiar_formulario()
    {
        txtcarnet1.setText("");
        txtnombre1.setText("");
        cbocurso1.removeAllItems();
        cbocurso1.addItem("Sistemas Operativos");
        cbocurso1.addItem("Programacion");
        cbocurso1.addItem("Base de datos");
        
        
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        // agregar validaciones respectivas
        
        conexion c = new conexion();
         try {
             c.conexion_db();
             c.eliminarAlumno(id);
             JOptionPane.showMessageDialog(null,"Alumno eliminado correctamente");
              jButton1.doClick();
             this.limpiar_formulario();
             
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(interfaz.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed
    private void limpiar(){
        txtcarnet.setText("");       
        txtnombre.setText("");
       
    }
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnreporte;
    private javax.swing.JComboBox<String> cbocurso;
    private javax.swing.JComboBox<String> cbocurso1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTPersonas;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtcarnet;
    private javax.swing.JTextField txtcarnet1;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnombre1;
    // End of variables declaration//GEN-END:variables
}
